### ISSUE TITLE
Dragonhunter Longbow skills do not appear in build page

### ISSUE THREAD

**Issue by Linkaaaaa** [HardstuckGuild/GW2-Tooltips.js#110]
Longbow gets detected correctly as equipped but the weapon skills do not appear in the build page

[https://hardstuck.gg/gw2/builds/?b=EoAq\~ru\~Xb\~6LnAGqAGNnAGqAGgSFcaHFOCQPCBZHTCGWzYvIGMJFvICMJ\~__
](https://hardstuck.gg/gw2/builds/?b=EoAq~ru~Xb~6LnAGqAGNnAGqAGgSFcaHFOCQPCBZHTCGWzYvIGMJFvICMJ~__
)
![7369](https://github.com/HardstuckGuild/GW2-Tooltips.js/assets/23245218/6e3e99a1-1df8-47e0-ab67-c87937f37813)

**Comment by SaculRennorb** [comment]
Alright, found the issue. Its on the API again, and I'm currently debating on how to address it. 

The original API uses both `BowLong` and `Longbow` in different places. We always Use `BowLong` but I'm not going to lie, we should probably just always use `Longbow and put the` old behavior behind a version flag.
